### ISSUE TITLE
Failed to parse inline template: undefined local variable or method `arch'

### ISSUE THREAD

**Issue by djjudas21** [xaque208/puppet-pxe#34] opened 2017-01-12 10:05 UTC
We just upgraded to Puppet Enterprise 2016.5 and found that our pxe stuff doesn't work any more. I don't really understand the error - I can't see anything obviously wrong in `pxe/installer.pp:31` or `permute/init.pp:19` otherwise I'd fix it myself.

Please could you take a look? I'm happy to test any patches etc. Thanks.

```
[jg4461@pxe ~]$ sudo puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Failed to parse inline template: undefined local variable or method `arch' for #<Puppet::Parser::TemplateWrapper:0x68828213> at /etc/puppetlabs/code/environments/pe/modules/pxe/manifests/installer.pp:31:20 at /etc/puppetlabs/code/environments/pe/modules/permute/manifests/init.pp:19 on node pxe.resnet.bris.ac.uk
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

**Comment by xaque208** [comment] 2017-01-12 20:06
Thanks for the report.  We need to get rid of permute from this module.

What version of puppet and facter are in the PE release you mention?

**Comment by UoB-Matt** [comment] 2017-01-26 16:38
Seeing the same issue.  Puppet 4.8.1 and Facter 3.5.0.

**Comment by xaque208** [comment] 2017-01-26 21:45
Oh, may I have the manifest that you are using also?  I'll try to get a test going so I can reproduce the issue.

**Comment by xaque208** [comment] 2017-01-26 23:45
@djjudas21 and @UoB-Matt If either of you are using the permute function to generate resource, could you please read the README update in PR #37 to make sure that a) it makes sense in teh Puppet 4 world for you, and perhaps b) test it?  If that looks good, then I can clean up example code that used permute, and replace it with the more modern language constructs.

**Comment by djjudas21** [comment] 2017-01-27 09:30
Yes it looks like we are using the old syntax in #37:

```puppet
  # Load base pxe config from zleslie/pxe
  include ::pxe

  # Set up a hash of permutations of distros and versions
  permute { 'CentOS Installers':
    resource => 'pxe::installer',
    unique   => {
      arch => 'x86_64',
      ver  => ['6','7'],
      os   => 'centos',
    },
    common   => {
      file    => 'os_<%= @os %>',
      kernel  => 'images/<%= @os %>/<%= @ver %>/<%= @arch %>/vmlinuz',
      append  => 'initrd=images/<%= @os %>/<%= @ver %>/<%= arch %>/initrd.img ramdisk_size=100000 asknetwork url --url=http://packages.bris.ac.uk/mirrors/CentOS/<%= @ver %>/os/<%= @arch %>/',
      baseurl => 'http://packages.bris.ac.uk/mirrors/CentOS/<%= @ver %>/os/<%= @arch %>/images/pxeboot',
    },
  }
```

So will I be able to switch to this new syntax in `zleslie/pxe 0.2.0`?

**Comment by xaque208** [comment] 2017-01-27 23:18
Ah, there is a bug in the line you have `arch`, it should read `@arch`.  Is that a copy paste from somewhere in this repo?

Also, if you are able, I'd love to know if the new syntax works for you.

**Comment by djjudas21** [comment] 2017-01-30 10:18
I don't think I copied the mistake, apparently it was of my own doing. Replacing the `@` worked, thanks.

I'll spin up a separate branch to test the new syntax. Will that "just work" with tagged release `0.2.0` or do I need to grab a newer version from git?

**Comment by xaque208** [comment] 2017-01-30 17:23
@djjudas21 `0.2.0` should work for that syntax, but I'll cut a new release for the recent changes.

**Comment by xaque208** [comment] 2017-01-30 17:24
@UoB-Matt Since you also mentioned you are having an issue, can you produce the manifest that you are using please?  A suspect a similar bug in the manifest.

**Comment by UoB-Matt** [comment] 2017-01-31 09:08
@xaque208 Same issue.  Thanks for your help.

**Comment by xaque208** [comment] 2017-01-31 17:38
Cool, I'll close this out.  If the readme update in #37 gets tested, I'd appreciate an update on #37 indicating such.  Thanks.

**Closed by xaque208** 2017-01-31 17:38 UTC
